### ISSUE TITLE
Completion error. You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by kangshung** [knight42/kopilot#13]
I assigned the openai api key to the KOPILOT_TOKEN env variable, and when I try to audit or diagnose any of the pods, I get the following error:

![Screenshot_20230402_214903](https://user-images.githubusercontent.com/47540509/229375655-29c70290-4592-4f4d-93d8-5211d8ecf30b.png)

Both the key and account are new, with a lot of free requests yet to be sent. What do I do wrong?

**Comment by knight42** [comment]
@kangshung Hi, this error might be caused by the object size of a pod, as `kopilot` will include the yaml of a pod in the prompt and right now the token limit for gpt-35-turbo model is 4096 tokens. I have tried to prune the object https://github.com/knight42/kopilot/pull/12, stripping any annotations and labels. 

I am still trying to figure out a better way to tackle this problem, but my openai account was deactivated, so it might take some time.

**Comment by knight42** [comment]
@kangshung Hi, I believe #15 should mitigate this issue, would you like to upgrade kopilot to 0.0.3 to see if this remains to be a problem?

**Comment by kangshung** [comment]
Hi @knight42, actually the problem was probably not with the plugin itself but with my openai account and API key. I thought that the free trial for API calls could be renewed on the new account, but it seems it's not (probably because of the same phone number I used for the old account which has no more free trial API calls).

So basically it's a subscription problem on my end. However, thanks for trying to help :)

Btw. you could add `version` command to check the version of the plugin quicker.
